version: "3.3"

services:  

  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb    
    volumes:
      - ./../logs/mongobingo/data:/data/db
      - ./../logs/mongobingo/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=Abcdf
      - MONGO_INITDB_ROOT_USERNAME=BingoBongo
    command: mongod
    networks:
      pubapi:
        aliases:
          - mongodb

  backend:
    image: backend
    build: ./backend
    container_name: backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:
      - mongodb     
    depends_on:     
      - mongodb             
    ports:
      - '8080:8080'    
    networks:
      - pubapi    
      
     
  frontend:    
   image: frontend 
   build: ./frontend                
   container_name: frontend
   links:
      - backend
   environment:
    - JVM_OPTS=-Xmx1g -Xms1g -XX:MaxPermSize=4g
    - CATALINA_OPTS=-Xmx1g -Xms1g -XX:MaxPermSize=4g 
   ports:
    - '9000:9000'  
   networks:
    - pubapi

networks:
  pubapi:
    driver: bridge
